### ISSUE TITLE
Crash 1.18.2

### ISSUE THREAD

**Issue by mxnmnm** [minecraftabnormals/Upgrade-Aquatic#369] opened 2023-06-03 09:19 UTC
https://gist.github.com/mxnmnm/4be1548727eb1e138ff8ff725a657a43

Randomly crashed

**Comment by V972** [comment] 2023-09-03 16:40
I have the same crash, but it happens when Thrasher grabs me.
But it happens inconsistently.

**Comment by bageldotjpg** [comment] 2023-09-14 22:51
Duplicate of #349

**Closed as completed by bageldotjpg** 2023-09-14 22:51 UTC
