### ISSUE TITLE
On rare occasions sonar beams appear offset from the thrasher's mouth

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Upgrade-Aquatic#163] opened 2020-07-23 02:14 UTC
![image](https://user-images.githubusercontent.com/38932715/88246510-94411f80-cc4f-11ea-9565-39a58f2e6ffa.png)

**Comment by SmellyModder** [comment] 2020-07-31 06:37
Unfortunately, there isn't a simple fix for this and is caused by vanilla's rotation controller not syncing the rotations to the client often enough. To fix this I'd need to implement a custom way of setting the rotations on the Thrasher, which could be icky since it may mess up existing things.
To make this better I've increased the speed at which the Thrasher turns to the target to fire the sonar, this helps the syncing by making the server update the rotations to the client more often.

**Closed by SmellyModder** 2020-07-31 06:37 UTC
Labels: Bug?, Indev Beta
