### ISSUE TITLE
Upgrade Aquatic says it's not compatible with Blueprint on 1.20.1

### ISSUE THREAD

**Issue by katubug** [minecraftabnormals/Upgrade-Aquatic#399] opened 2024-04-29 18:26 UTC
On MC 1.20.1, when adding Upgrade Aquatic version 6.0.0, it won't load because it wants a different Blueprint version. I have tried both Blueprint 7.0.3 and 7.0.1.

I get this error:
```
[13:24:55] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'blueprint', Requested by: 'upgrade_aquatic', Expected range: '[7.1.0,)', Actual version: '7.0.1'
```

**Comment by katubug** [comment] 2024-04-29 18:45
I am having the same issue with Neapolitan and Incubation, actually.
```
[13:43:41] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'blueprint', Requested by: 'neapolitan', Expected range: '[7.1.0,)', Actual version: '7.0.3'
	Mod ID: 'blueprint', Requested by: 'incubation', Expected range: '[7.1.0,)', Actual version: '7.0.3'
```

Let me know if you want separate issues for those.

**Comment by bageldotjpg** [comment] 2024-04-29 23:09
Duplicate of #395

**Closed as completed by bageldotjpg** 2024-04-29 23:09 UTC
