### ISSUE TITLE
crash 1.19.2

### ISSUE THREAD

**Issue by vanek785** [minecraftabnormals/Upgrade-Aquatic#375] opened 2023-08-02 19:21 UTC
[crash-2023-08-02_22.08.39-server.txt](https://github.com/team-abnormals/upgrade-aquatic/files/12243935/crash-2023-08-02_22.08.39-server.txt)

**Comment by bageldotjpg** [comment] 2023-09-14 22:52
Duplicate of #349

**Closed as completed by bageldotjpg** 2023-09-14 22:52 UTC
