### ISSUE TITLE
[1.19.2] Phantoms not descending to attack

### ISSUE THREAD

**Issue by MistereMoth** [minecraftabnormals/Upgrade-Aquatic#357] opened 2023-03-22 17:24 UTC
I just played on my 1.19.2 modpack with many mods and phantoms aren't descending to attack, just attacking my ears with their noises, so i can only kill them with projectiles which most of the time won't even land on them.
Since this is the only mod that touches on phantoms i'm pretty sure it's the culprit, for the sake of my hearing please fix it

**Comment by SmellyModder** [comment] 2023-03-22 18:56
Phantoms only attack players who are insomniacs. This is an intended feature of the mod.
Are you an insomniac when they're not attacking you?

**Comment by MistereMoth** [comment] 2023-03-22 21:34
yes i haven't found sheeps yet to make a bed

**Comment by thelegitdolt** [comment] 2023-03-23 04:29
can reproduce, phantoms are spawning + not attacking me even though i have not slept in multiple days

**Comment by SmellyModder** [comment] 2023-03-23 13:28
Do you know if the insomnia overlay still appears ever? I only ask this because the stat for time since sleep might not be correctly updated.

**Comment by MistereMoth** [comment] 2023-03-23 14:01
no i don't know

but it might appear since it seems like that they try to descend to attack me but stop and does some very erratic movement

**Comment by thelegitdolt** [comment] 2023-03-23 19:55
@SmellyModder Not seeing an insomnia overlay. Definitely lots of phantoms overhead though

**Comment by bageldotjpg** [comment] 2023-04-01 20:58
Pet Cemetery issue. Fixed in latest Pet Cemetery release.

**Closed as completed by bageldotjpg** 2023-04-01 20:58 UTC

**Comment by MistereMoth** [comment] 2023-04-16 17:18
yeah it's fixed now. 
but now every mob except for phantoms and wandering traders has an extremely low spawn rate, i barely ever see them, i'd make a post about it but i don't even know from which mod it is, weirdly enough it didn't happen at the start of my playthrough, just after updating the mods and adding some new ones
