### ISSUE TITLE
crash client 1.19.2 forge

### ISSUE THREAD

**Issue by GitJhopa** [minecraftabnormals/Upgrade-Aquatic#377] opened 2023-08-09 19:16 UTC
[crash-2023-08-09_21.08.26-client.txt](https://github.com/team-abnormals/upgrade-aquatic/files/12306164/crash-2023-08-09_21.08.26-client.txt)

**Comment by bageldotjpg** [comment] 2023-09-14 22:52
Duplicate of #362

**Closed as completed by bageldotjpg** 2023-09-14 22:52 UTC
