### ISSUE TITLE
1.14.4 Server Crash.

### ISSUE THREAD

**Issue by Wissi** [minecraftabnormals/Upgrade-Aquatic#34] opened 2019-11-11 03:41 UTC
Awesome Mod, we love it. 
Great work.

We recently ran into a server crash stating:
`java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_222] {}
	at net.minecraft.tags.Tag.func_205596_a(Tag.java:73) ~[?:?] {re:classloading}
	at com.teamabnormals.upgrade_aquatic.core.events.LootEvents.addDrops(LootEvents.java:56) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_494_LootEvents_addDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:351) ~[?:?] {re:classloading}`

Full crash log [here](https://gist.github.com/Wissi/06bbd825b7d55c86a58f7ace59c4cc4d).

Using:
Forge 28.1.87
Upgrade Aquatic Wave Three v6 - Beta 1.0.8
Full Modpack info here: [Minecolonies 1.14.4 Testpack v 1.6](https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack-ver-1-11-2).

Hope it helps.

**Comment by five0five** [comment] 2019-11-11 15:25
this is a very rare crash that occurs due to the drowned drop corals feature, you most likely won't come across it again and the feature will be replaced in favour of something more unique next update

**Comment by SmellyModder** [comment] 2019-11-14 20:51
This is a duplicate of #23

**Closed by SmellyModder** 2019-11-14 20:51 UTC
Labels: duplicate
