### ISSUE TITLE
Server is crashing when trasher is attacking

### ISSUE THREAD

**Issue by Moldx3** [minecraftabnormals/Upgrade-Aquatic#382] opened 2023-10-10 15:55 UTC
Hey,
i am experiencing issues with the trasher.
Nearly always when it attacks and grabs a player and throwing him around the server crashes.
I've just updated forge, upgrade aquatic and blueprint and the issue is still present.
[crash-2023-10-10_15.49.47-server.txt](https://github.com/team-abnormals/upgrade-aquatic/files/12859206/crash-2023-10-10_15.49.47-server.txt)

**Comment by xkobalx** [comment] 2023-11-09 18:57
Can confirm we are having the same issue with mod version 5.1.0 on MC 1.19.2 running Forge version 43.2.21 on MP Server. The issue only effect the Thrasher and not the Great Thrasher. If it grabs a player, the server crashes after a second or two. Can't remove mod without corrupting world. Had to add a repeating command block to constantly kill thrashers to prevent the crash.

**Comment by jaynesb** [comment] 2023-11-11 22:52
I'm seeing it affect Great Thrashers as well.
[crash-2023-11-11_14.44.48-server.txt](https://github.com/team-abnormals/upgrade-aquatic/files/13326722/crash-2023-11-11_14.44.48-server.txt)

**Comment by prismaticNett** [comment] 2023-12-05 01:47
I had a similar problem on my server  with upgrade_aquatic 1.18.2-4.0.0 and blueprint 1.18.2-5.5.0 on forge 40.2.9
[crash-2023-12-05_00.05.05-server.txt](https://github.com/team-abnormals/upgrade-aquatic/files/13553760/crash-2023-12-05_00.05.05-server.txt)
the crash log looks pretty identical but one of our players fought thrashers and got grabbed twice without the game crashing--the closest person to the thrasher was foggyboots and he was on an island

**Comment by Aceplante** [comment] 2024-01-22 06:05
Same

**Comment by Gunner76th** [comment] 2024-02-09 02:25
this is a duplicate of https://github.com/team-abnormals/upgrade-aquatic/issues/349

**Comment by ModernGamingWorld** [comment] 2024-04-03 23:36
@teamabnormals Is there a fix for this on 1.19.2? I just had this happen to a few people playing my custom modpack and was wondering when will this be fixed so that they don't have to keep disabling the mod

**Closed as completed** 2024-04-30 04:58 UTC

**Comment by DoctorMage** [comment] 2024-05-07 21:43
Are there any plans on porting the fix to 1.19.2 as well instead of just 1.20
