### ISSUE TITLE
{Forge 1.20.1] Mod requires a version of Blueprint that doesn't exist

### ISSUE THREAD

**Issue by vizthex123** [minecraftabnormals/Upgrade-Aquatic#396] opened 2024-04-28 03:53 UTC
It wants v7.1.0, but the latest version is v7.0.3.

Log:
[latest.log](https://github.com/team-abnormals/upgrade-aquatic/files/15140693/latest.log)

**Comment by bageldotjpg** [comment] 2024-04-28 05:05
Duplicate of #395

**Closed as completed by bageldotjpg** 2024-04-28 05:05 UTC
